export const url = 'https://backend-flax-six.vercel.app/'
export const TODOS = 'todos'
export const QUEUE = 'queue'
export const CREATE = 'create'
export const DELETE = 'delete'
export const UPDATE = 'update'